server:
  port: 80
spring:
  application:
    name: git-springboot
  datasource:
    url: jdbc:mysql://127.0.0.1/db2020
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver